# Generated by Django 5.0 on 2024-05-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_keyword_alter_career_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='overview',
            new_name='name',
        ),
        migrations.AddField(
            model_name='career',
            name='overview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
